### PR TITLE
small optimization in the screen rendering

### PR DESCRIPTION
**Pull request by artrag**
I removed some redundancy in the rendering loop
Look at MRC for details

### CODE REVIEW

**Comment by artrag** [comment]
I'm not very expert on Git

**Comment by artrag** [comment]
I hope it worked

**Comment by santiontanon** [comment]
yeah! it did!! Thanks a lot! it’s already in, and I’ve already started experimenting with the “outi” unrolling. It saves A LOT of CPU time, but in MSX1 it’s glitching a bit in the lower part of the screen some times (I guess sometimes it does not have time to make it all the way down the screen before the next vertical refresh). I’ll be playing with it in the next few days though :)

santi

**Comment by artrag** [comment]
About optimizations I was removing a full bunch of and a that were not needed due to the fact the zero flag was already set by previous instructions.
Note also that in your rle code you can use ret p as exit instead of JP p,exit

**Comment by artrag** [comment]
Just few questions about rom usage. I see you use the for anything. The decoder is short and works fine for level maps. 
It works very poor for tileset and sprites, where msx-o-mizer or pletter would work uniformly better.
Is it a constrained choice for some reason? I expect a huge saving in rom size that would compensate the extra size of the unpacker

**Comment by artrag** [comment]
About music and sfx you are using custom made code instead of pt3 player and aysfx player.
The main advantage of those tools are the windows editors and the large libraries of music and effects available on the net.
You can also compress the pt3 files and unpack them in ram when needed. Now I see your data stored in plain. Probably if you want to add in game music, compression could be an option, especially if you add general compression like the above I mentioned

**Pull request merged**
